DRIVING_POLICY:
  ACCEPTANCE_RADIUS: 0.15
  CONTROL_SATURATION: 0.9
  PERCENTAGE_OF_TRAINING_DATA: 80
  PID:
    DERIVATIVE_GAIN_DIST: 0.1
    DERIVATIVE_GAIN_HEADING: 1.0
    FORWARD_MIN_ANGLE: 0.5
    PROPORTIONAL_GAIN_DIST: 4.0
    PROPORTIONAL_GAIN_HEADING: 4.25
  PILOT_NET:
    PATH: ./models/test.tflite
OPENBOT:
  OPENBOT_PAWN:
    ACTION_SCALE: 255
    ANIM_INSTANCE: /OpenBot/V0/Meshes/OpenBot_V0_Animation.OpenBot_V0_Animation_C
    BATTERY_VOLTAGE: 12.0
    CAMERA_COMPONENT:
      FOV: 70.0
      PITCH: 0.0
      POSITION_X: 5.0
      POSITION_Y: 5.0
      POSITION_Z: 5.0
      ROLL: 0.0
      YAW: 0.0
    CONTROL_DEAD_ZONE: 2.5
    ELECTRICAL_INDUCTANCE: 0.5
    ELECTRICAL_RESISTANCE: 0.5
    GEAR_RATIO: 50.0
    IMU_COMPONENT:
      PITCH: 0.0
      POSITION_X: 5.0
      POSITION_Y: 0.0
      POSITION_Z: 5.0
      ROLL: 0.0
      YAW: 0.0
    MOTOR_TORQUE_MAX: 0.19
    MOTOR_VELOCITY_CONSTANT: 65.89
    SKELETAL_MESH: /OpenBot/V0/Meshes/OpenBot_V0_Mesh.OpenBot_V0_Mesh
    SONAR_COMPONENT:
      PITCH: 0.0
      POSITION_X: 10.0
      POSITION_Y: 0.0
      POSITION_Z: -1.5
      ROLL: 0.0
      YAW: 0.0
    VEHICLE_COMPONENT:
      CHASSIS_HEIGHT: 15.0
      CHASSIS_WIDTH: 15.0
      DRAG_COEFFICIENT: 1.0
      MASS: 1.12
      MOTOR_MAX_RPM: 20000.0
  OPENBOT_WHEEL:
    AFFECTED_BY_HANDBRAKE: true
    MASS: 0.033
    SHAPE_RADIUS: 6.3
    SHAPE_WIDTH: 2.5
    STEER_ANGLE: 0.0
    SUSPENSION_MAX_DROP: 0.0
    SUSPENSION_MAX_RAISE: 0.0
SIMULATION_CONTROLLER:
  AGENT: OpenBotAgent
  CAMERA_AGENT:
    ACTION_COMPONENTS:
    - set_pose
    - set_num_random_points
    CAMERA:
      ACTOR_NAME: ''
      FOV: 90.0
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      RENDER_PASSES:
      - final_color
    NAVMESH:
      AGENT_HEIGHT: 1.0
      AGENT_MAX_SLOPE: 1.0
      AGENT_MAX_STEP_HEIGHT: -1.0
      AGENT_RADIUS: 1.0
      CELL_HEIGHT: 1.0
      CELL_SIZE: 1.0
      EXPORT_NAV_DATA_OBJ: false
      EXPORT_NAV_DATA_OBJ_DIR: ''
      MAX_SIMPLIFICATION_ERROR: 1.3
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 0.0
      NAV_MODIFIER_OFFSET_X: 0.0
      NAV_MODIFIER_OFFSET_Y: 0.0
      NAV_MODIFIER_OFFSET_Z: 0.0
      TILE_POOL_SIZE: 1024
      TILE_SIZE_UU: 1
      WORLD_BOUND_TAG_NAMES:
      - architecture
      - furniture
    OBSERVATION_COMPONENTS:
    - camera
    STEP_INFO_COMPONENTS:
    - random_points
  CAMERA_SENSOR:
    FINAL_COLOR_AUTO_EXPOSURE_SPEED_DOWN: 9999.0
    FINAL_COLOR_AUTO_EXPOSURE_SPEED_UP: 9999.0
    FINAL_COLOR_INDIRECT_LIGHTING_INTENSITY: 1.0
    FINAL_COLOR_OVERRIDE_AUTO_EXPOSURE_SPEED_DOWN: true
    FINAL_COLOR_OVERRIDE_AUTO_EXPOSURE_SPEED_UP: true
    FINAL_COLOR_OVERRIDE_INDIRECT_LIGHTING_INTENSITY: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO_INTENSITY: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO_RADIUS: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO_SAMPLES_PER_PIXEL: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_GI: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_GI_MAX_BOUNCES: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_GI_SAMPLES_PER_PIXEL: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_MAX_BOUNCES: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_MAX_ROUGHNESS: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_SAMPLES_PER_PIXEL: true
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_TRANSLUCENCY: true
    FINAL_COLOR_OVERRIDE_REFLECTIONS_TYPE: true
    FINAL_COLOR_RAYTRACING_AO: 1
    FINAL_COLOR_RAYTRACING_AO_INTENSITY: 0.8
    FINAL_COLOR_RAYTRACING_AO_RADIUS: 4000.0
    FINAL_COLOR_RAYTRACING_AO_SAMPLES_PER_PIXEL: 8
    FINAL_COLOR_RAYTRACING_GI_MAX_BOUNCES: 4
    FINAL_COLOR_RAYTRACING_GI_SAMPLES_PER_PIXEL: 16
    FINAL_COLOR_RAYTRACING_GI_TYPE: BruteForce
    FINAL_COLOR_RAYTRACING_REFLECTIONS_MAX_BOUNCES: 2
    FINAL_COLOR_RAYTRACING_REFLECTIONS_MAX_ROUGHNESS: 0.4
    FINAL_COLOR_RAYTRACING_REFLECTIONS_SAMPLES_PER_PIXEL: 8
    FINAL_COLOR_RAYTRACING_REFLECTIONS_TRANSLUCENCY: 1
    FINAL_COLOR_REFLECTIONS_TYPE: RayTracing
    FINAL_COLOR_SET_AMBIENT_OCCLUSION: true
    FINAL_COLOR_SET_ANTI_ALIASING: true
    FINAL_COLOR_SET_CAMERA_IMPERFECTIONS: true
    FINAL_COLOR_SET_COLOR_GRADING: true
    FINAL_COLOR_SET_DEPTH_OF_FIELD: true
    FINAL_COLOR_SET_DISTANCE_FIELD_AO: true
    FINAL_COLOR_SET_DYNAMIC_SHADOWS: true
    FINAL_COLOR_SET_EYE_ADAPTATION: true
    FINAL_COLOR_SET_GRAIN: true
    FINAL_COLOR_SET_INDIRECT_LIGHTING_CACHE: true
    FINAL_COLOR_SET_LENS_FLARES: true
    FINAL_COLOR_SET_LIGHT_SHAFTS: true
    FINAL_COLOR_SET_RAYTRACED_DISTANCE_FIELD_SHADOWS: true
    FINAL_COLOR_SET_SCREEN_SPACE_REFLECTIONS: true
    FINAL_COLOR_SET_SEPARATE_TRANSLUCENCY: true
    FINAL_COLOR_SET_TEMPORAL_AA: true
    FINAL_COLOR_SET_VIGNETTE: true
    FINAL_COLOR_USE_RAYTRACING_IF_ENABLED: true
  CUSTOM_UNREAL_CONSOLE_COMMANDS: []
  IMITATION_LEARNING_TASK:
    AGENT_ACTOR_NAME: OpenBotAgent
    GET_POSITIONS_FROM_TRAJECTORY_SAMPLING: true
    GOAL_ACTOR_NAME: GoalActor
    NAVMESH:
      AGENT_HEIGHT: 20.0
      AGENT_MAX_STEP_HEIGHT: 1.0
      AGENT_RADIUS: 20.0
    OBSTACLE_IGNORE_ACTOR_NAMES:
    - Floor
    - obj0
    - VehicleMesh
    POSITIONS_FILE: /home/quentin/Desktop/ISL/spear/examples/openbot/imitation_learning/start_goal_coordinates.csv
    TRAJECTORY_SAMPLING_DEBUG_RENDER: false
    TRAJECTORY_SAMPLING_MAX_ITERS: 100
    TRAJECTORY_SAMPLING_SEARCH_RADIUS: 10000
  IMU_SENSOR:
    ACCELEROMETER_NOISE_STD_DEV:
      X: 0.0
      Y: 0.0
      Z: 0.0
    DEBUG_RENDER: false
    GYROSCOPE_BIAS:
      X: 0.0
      Y: 0.0
      Z: 0.0
    GYROSCOPE_NOISE_STD_DEV:
      X: 0.0
      Y: 0.0
      Z: 0.0
  IP: 127.0.0.1
  LEVEL_NAME: /Game/Maps/Map_235554690
  MAX_NUM_TICKS_AFTER_RESET: 10
  OPENBOT_AGENT:
    ACTION_COMPONENTS:
    - apply_voltage
    CAMERA:
      FOV: 70.0
      IMAGE_HEIGHT: 120
      IMAGE_WIDTH: 160
      RENDER_PASSES:
      - final_color
    IS_READY_VELOCITY_THRESHOLD: 1.0
    NAVMESH:
      AGENT_HEIGHT: 20.0
      AGENT_MAX_SLOPE: 0.1
      AGENT_MAX_STEP_HEIGHT: 1.0
      AGENT_RADIUS: 20.0
      CELL_HEIGHT: 1.0
      CELL_SIZE: 1.0
      EXPORT_NAV_DATA_OBJ: false
      EXPORT_NAV_DATA_OBJ_DIR: ''
      MAX_SIMPLIFICATION_ERROR: 1.3
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 400.0
      NAV_MODIFIER_OFFSET_X: 0.0
      NAV_MODIFIER_OFFSET_Y: 0.0
      NAV_MODIFIER_OFFSET_Z: 20.0
      TILE_POOL_SIZE: 1024
      TILE_SIZE_UU: 300
      WORLD_BOUND_TAG_NAMES:
      - architecture
      - furniture
    OBSERVATION_COMPONENTS:
    - state_data
    - control_data
    - camera
    - imu
    - sonar
    OPENBOT_ACTOR_NAME: OpenBotAgent
    STEP_INFO_COMPONENTS:
    - trajectory_data
    TRAJECTORY_DATA:
      GOAL_ACTOR_NAME: GoalActor
  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: ''
    EPISODE_BEGIN:
      AGENT_POSITION_X_MAX: .nan
      AGENT_POSITION_X_MIN: .nan
      AGENT_POSITION_Y_MAX: .nan
      AGENT_POSITION_Y_MIN: .nan
      AGENT_POSITION_Z: .nan
      GOAL_POSITION_X_MAX: .nan
      GOAL_POSITION_X_MIN: .nan
      GOAL_POSITION_Y_MAX: .nan
      GOAL_POSITION_Y_MIN: .nan
      GOAL_POSITION_Z: .nan
      SPAWN_DISTANCE_THRESHOLD: 1.0
    GOAL_ACTOR_NAME: ''
    GOAL_MATERIAL: /SimulationController/Materials/Goal_MAT.Goal_MAT
    GOAL_MESH: /Engine/BasicShapes/Cylinder.Cylinder
    GOAL_SCALE: 0.5
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    RANDOM_SEED: 0
    REWARD:
      DISTANCE_TO_GOAL_SCALE: 1.0
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
  PORT: 30000
  SCENE_ID: '235554690'
  SIMULATION_STEP_TIME_SECONDS: 0.033
  SONAR_SENSOR:
    DEBUG_RENDER: false
    HORIZONTAL_FOV: 30.0
    MAX_REFLECTION_ANGLE: 45.0
    NOISE_STD_DEV: 0.0
    NUM_RAYS: 21
    RANGE:
      MAX: 10.0
      MIN: 0.01
    VERTICAL_FOV: 10.0
  SPHERE_AGENT:
    ACTION_COMPONENTS:
    - apply_force
    APPLY_FORCE:
      FORCE_SCALE: 1.0
      ROTATE_SCALE: 1.0
    CAMERA:
      ACTOR_NAME: ''
      FOV: 90.0
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      POSITION_OFFSET_X: 0.0
      POSITION_OFFSET_Y: 0.0
      POSITION_OFFSET_Z: 5.0
      RENDER_PASSES:
      - final_color
    COMPASS:
      GOAL_ACTOR_NAME: ''
      LINEAR_VELOCITY_SCALE: 1.0
      OFFSET_TO_GOAL_SCALE: 1.0
      YAW_SCALE: 1.0
    OBSERVATION_COMPONENTS:
    - compass
    - camera
    SPHERE:
      ACTOR_NAME: ''
      ANGULAR_DAMPING: 0.0
      LINEAR_DAMPING: 0.0
      MASS_SCALE: 1.0
      MATERIAL: /SimulationController/Materials/Agent_MAT.Agent_MAT
      MAX_ANGULAR_VELOCITY: 1.0
      MESH_SCALE: 0.5
      STATIC_MESH: /Engine/BasicShapes/Sphere.Sphere
    STEP_INFO_COMPONENTS:
    - debug_info
  TASK: ImitationLearningTask
  VISUALIZER:
    ACTOR_NAME: OpenBotAgent
    SPAWN_CAMERA: false
    SPAWN_CAMERA_ORIENTATION_PITCH: -35.0
    SPAWN_CAMERA_ORIENTATION_ROLL: 0.0
    SPAWN_CAMERA_ORIENTATION_YAW: 0.0
    SPAWN_CAMERA_POSITION_X: -50.0
    SPAWN_CAMERA_POSITION_Y: 0.0
    SPAWN_CAMERA_POSITION_Z: 40.0
  WORLD_PATH_NAME: /Game/Maps/Map_235554690.Map_235554690
SPEAR:
  CONTENT_DIR: /home/quentin/Desktop/ISL/spear/cpp/unreal_projects/SpearSim/Standalone-Shipping/LinuxNoEditor/SpearSim/Content
  CUSTOM_COMMAND_LINE_ARGUMENTS: []
  DATA_DIR: /home/quentin/Desktop/ISL/spear_data/v7
  GPU_ID: 0
  LAUNCH_MODE: standalone_executable
  RENDER_OFFSCREEN: false
  RPC_CLIENT_AFTER_INITIALIZE_CONNECTION_SLEEP_TIME_SECONDS: 1.0
  RPC_CLIENT_INITIALIZE_CONNECTION_MAX_TIME_SECONDS: 120.0
  RPC_CLIENT_INITIALIZE_CONNECTION_SLEEP_TIME_SECONDS: 1.0
  RPC_CLIENT_INTERNAL_RECONNECT_LIMIT: 1
  RPC_CLIENT_INTERNAL_TIMEOUT_SECONDS: 5.0
  STANDALONE_EXECUTABLE: /home/quentin/Desktop/ISL/spear/cpp/unreal_projects/SpearSim/Standalone-Shipping/LinuxNoEditor/SpearSim.sh
  TEMP_DIR: tmp
  UNREAL_EDITOR_EXECUTABLE: ''
  UNREAL_INTERNAL_LOG_FILE: ''
  UPROJECT: ''
  VULKAN_DEVICE_FILES: /usr/share/vulkan/icd.d/nvidia_icd.json
  WINDOW_RESOLUTION_X: 640
  WINDOW_RESOLUTION_Y: 480
