INTERIORSIM:
  LAUNCH_MODE: "standalone_executable"
  STANDALONE_EXECUTABLE: "C:/Users/ADAS/repos/interiorsim/code/unreal_projects/SimpleSim/ArchivedBuilds/WindowsNoEditor/SimpleSim/Binaries/Win64/SimpleSim-Cmd.exe"
  TEMP_DIR: "C:/Users/ADAS/repos/interiorsim/code/unreal_projects/SimpleSim/Temp"

SIMULATION_CONTROLLER:
  TASK: "PointGoalNavigationTask"
  AGENT: "SimpleSimAgentController"

  SPHERE_AGENT:
    SPHERE_ACTOR_NAME: "Sphere"
    ACTION_COMPONENTS: ["apply_force"] # "apply_force"
    OBSERVATION_COMPONENTS: ["compass", "camera"] # "compass", "camera"
    STEP_INFO_COMPONENTS: ["debug_info"] # "debug_info"
    COMPASS:
      GOAL_ACTOR_NAME: "Goal"
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0
      YAW_SCALE: 1.0
    CAMERA:
      CAMERA_ACTOR_NAME: "CameraActor"
      RENDER_PASSES: ["final_color"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0
      POSITION_OFFSET_X: 0.0
      POSITION_OFFSET_Y: 0.0
      POSITION_OFFSET_Z: 5.0
    APPLY_FORCE:
      FORCE_SCALE: 1.0
      ROTATE_SCALE: 1.0
    SPHERE:
      MASS_SCALE: 1.0
      MAX_ANGULAR_VELOCITY: 1.0
      LINEAR_DAMPING: 0.0
      ANGULAR_DAMPING: 0.0

  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: "Sphere"
    GOAL_ACTOR_NAME: "Goal"
    REWARD:
      HIT_GOAL: 100.0
      HIT_OBSTACLE: -100.0
      DISTANCE_TO_GOAL_SCALE: 0.00001
    EPISODE_BEGIN:
      AGENT_POSITION_X_MIN: -150.0
      AGENT_POSITION_X_MAX: 150.0
      AGENT_POSITION_Y_MIN: -150.0
      AGENT_POSITION_Y_MAX: 150.0
      AGENT_POSITION_Z: 5.0
      GOAL_POSITION_X_MIN: -350.0
      GOAL_POSITION_X_MAX: 350.0
      GOAL_POSITION_Y_MIN: -350.0
      GOAL_POSITION_Y_MAX: 350.0
      GOAL_POSITION_Z: 5.0
      SPAWN_DISTANCE_THRESHOLD: 50.0
    OBSTACLE_IGNORE_ACTOR_NAMES: [ "Floor" ]

  VISUALIZER:
    ACTOR_NAME: "DebugCameraActor" # "DebugCameraActor" or "ObservationCameraActor"
    SPAWN_CAMERA: False

ROBOT_SIM:
  PIP_CAMERA_LOAD_SEGMENTATION_MATERIAL: False
