#
# Copyright(c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

SIMULATION_CONTROLLER:
  CAMERA_AGENT:
    NAVMESH:
      AGENT_RADIUS: 5.0
      AGENT_HEIGHT: 180.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: 1.0
      AGENT_MAX_SLOPE: 1.0
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 100.0
      TILE_SIZE_UU: 300
      TILE_POOL_SIZE: 1024
      MAX_SIMPLIFICATION_ERROR: 1.3
      NAV_MODIFIER_OFFSET_Z: 50.0
      BOUNDS_VOLUME_ACTOR_TAGS: ["architecture", "furniture"]
