UNREALAI:
  # launch unreal engine instance via different modes
  # "standalone_executable", or "uproject", or "running_instance"
  # "standalone_executable" - launches a packaged executable of an Unreal Engine project
  # "uproject" - launches an uproject with Unreal Engine editor executable
  # "running_instance" - connects to an already running instance of Unreal Engine
  LAUNCH_MODE: "standalone_executable"
  
  # If launch_mode is "standalone_exectuable", specify this path to an Unreal application.
  STANDALONE_EXECUTABLE: "/home/quentin/Desktop/interiorsim/code/unreal_projects/RobotProject/dist/LinuxNoEditor/RobotProject.sh"
  
  TEMP_DIR: "/home/quentin/Desktop/interiorsim/code/unreal_projects/RobotProject/Temp"


  # True if unreal engine instance should be launched in headless mode
  # Note: This flag is unused if your launch_mode is "running_instance"
  RENDER_OFFSCREEN: False
  
  # Specify the location of the settings.json parameter file used in the InteriorSim executable. 
  # Allows avoiding the "settings.json not found" error at simulation start:
  #CUSTOM_COMMAND_LINE_ARGUMENTS: ["-RobotSimSettingPath=/home/qleboute/Documents/Git/interiorsim/code/unreal_projects/RobotProject/dist/LinuxNoEditor/setting/settings.json", "-game"]
  CUSTOM_COMMAND_LINE_ARGUMENTS: ["-RobotSimSettingPath=/home/quentin/Desktop/interiorsim/code/unreal_projects/RobotProject/dist/LinuxNoEditor/setting/settings.json", "-game"]
  
  # Once a connection has been established, the RPC client will wait for this amount of
  # time before throwing when calling a server function.
  RPC_CLIENT_INITIALIZE_CONNECTION_MAX_TIME_SECONDS: 120.0
  RPC_CLIENT_INITIALIZE_CONNECTION_SLEEP_TIME_SECONDS: 10.0
  RPC_CLIENT_INTERNAL_RECONNECT_LIMIT: 5
  RPC_CLIENT_INTERNAL_TIMEOUT_SECONDS: 30.0
