#
# Copyright(c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

SIMULATION_CONTROLLER:
  URDFBOT_AGENT:
    SPAWN_MODE: "specify_pose" # "specify_pose", "specify_existing_actor"
    SPAWN_ACTOR_NAME: ""
    SPAWN_POSITION_X: -530.0
    SPAWN_POSITION_Y: 200.0
    SPAWN_POSITION_Z: 0.0
    SPAWN_PITCH: 0.0
    SPAWN_YAW: -90.0
    SPAWN_ROLL: 0.0
URDFBOT:
  URDFBOT_PAWN:
    CAMERA_COMPONENT:
      PITCH: -15.0
      POSITION_X: 50.0
      POSITION_Y: -200.0
      POSITION_Z: 120.0
      ROLL: 0.0
      YAW: 90.0
