SPEAR:

  # launch unreal engine instance via different modes
  # "standalone_executable", or "uproject", or "running_instance"
  # "standalone_executable" - launches a packaged executable of an Unreal Engine project
  # "uproject" - launches an uproject with Unreal Engine editor executable
  # "running_instance" - connects to an already running instance of Unreal Engine
  LAUNCH_MODE: "standalone_executable"
  
  # If launch_mode is "standalone_exectuable", specify this path to an Unreal application.
  #STANDALONE_EXECUTABLE: "/home/qleboute/Documents/Git/spear/code/unreal_projects/RobotProject/Standalone-Development/LinuxNoEditor/RobotProject.sh"
  #STANDALONE_EXECUTABLE: "/home/quentin/Desktop/ISL/spear/code/unreal_projects/RobotProject/Standalone-Shipping/LinuxNoEditor/RobotProject.sh"
  STANDALONE_EXECUTABLE: "/home/quentin/Desktop/ISL/spear/code/unreal_projects/RobotProject/Standalone-Development/LinuxNoEditor/RobotProject.sh"


  #TEMP_DIR: "/home/qleboute/Documents/Git/spear/code/unreal_projects/RobotProject/Temp"
  TEMP_DIR: "/home/quentin/Desktop/ISL/spear/code/unreal_projects/RobotProject/Temp"

  VULKAN_DEVICE_FILES: "/usr/share/vulkan/icd.d/nvidia_icd.json"

  # True if unreal engine instance should be launched in headless mode
  # Note: This flag is unused if your launch_mode is "running_instance"
  RENDER_OFFSCREEN: False
  
  # Specify the location of the settings.json parameter file used in the InteriorSim executable. 
  # Allows avoiding the "settings.json not found" error at simulation start:
  #CUSTOM_COMMAND_LINE_ARGUMENTS: ["-RobotSimSettingPath=/home/qleboute/Documents/Git/spear/code/unreal_projects/RobotProject/Standalone-Development/LinuxNoEditor/setting/settings.json"]
  CUSTOM_COMMAND_LINE_ARGUMENTS: []

  # Once a connection has been established, the RPC client will wait for this amount of
  # time before throwing when calling a server function.
  RPC_CLIENT_INITIALIZE_CONNECTION_MAX_TIME_SECONDS: 200.0
  RPC_CLIENT_INITIALIZE_CONNECTION_SLEEP_TIME_SECONDS: 10.0
  RPC_CLIENT_INTERNAL_RECONNECT_LIMIT: 10
  RPC_CLIENT_INTERNAL_TIMEOUT_SECONDS: 200.0
  
SIMULATION_CONTROLLER:
  PORT: 30001 
  TASK: "ImitationLearningTask"
  AGENT: "OpenBotAgent"

  SIMULATION_STEP_TIME_SECONDS: 0.033

  IMITATION_LEARNING_TASK:
    AGENT_ACTOR_NAME: "OpenBotAgent"
    GOAL_ACTOR_NAME: "GoalActor"
    OBSTACLE_IGNORE_ACTOR_NAMES: ["Floor", "obj0", "VehicleMesh"]
    GET_POSITIONS_FROM_TRAJECTORY_SAMPLING: True
    TRAJECTORY_DEBUG_RENDER: True
    TRAJECTORY_SAMPLING_SEARCH_RADIUS: 10000 # Radius in [m], of the region around the desination coordinates where the goal will be considered as "reached" by the agent. 
    TRAJECTORY_SAMPLING_MAX_ITERS: 5000
    NAVMESH:
      AGENT_RADIUS: 20.0
      AGENT_HEIGHT: 20.0
      AGENT_MAX_STEP_HEIGHT: 1.0
    POSITIONS_FILE: "/home/quentin/Desktop/ISL/spear/code/experimental/rl_openbot/imitation_learning/Trajectories/InitGoalAgentPositions_235388780.csv"
    #POSITIONS_FILE: "/home/qleboute/Documents/Git/spear/code/experimental/openbot/imitation_learning/Trajectories/InitGoalAgentPositions_235388780.csv"
    AUTOPILOT:
      PROPORTIONAL_GAIN_HEADING: 5.25 # PID proportional gain for the autopilot
      DERIVATIVE_GAIN_HEADING: 1.0    # PID derivative gain for the autopilot
      PROPORTIONAL_GAIN_DIST: 4.0     # PID proportional gain for the autopilot
      DERIVATIVE_GAIN_DIST: -0.1      # PID derivative gain for the autopilot
      FORWARD_MIN_ANGLE: 0.5          # Angular range within which the vehicle moves forward to the target in [rad]
      CONTROL_SATURATION: 0.9         # Saturates the ammount of linar (resp. angular) command before merging them into left/right wheels command
      ACCEPTANCE_RADIUS: 0.15         # Radius in [m], of the region around the desination coordinates where the goal will be considered as "reached" by the agent. 


  OPENBOT_AGENT:
    OPENBOT_ACTOR_NAME: "OpenBotAgent"
    TRAJECTORY_DATA:
      GOAL_ACTOR_NAME: "GoalActor"
    ACTION_COMPONENTS: ["apply_voltage"] # "apply_voltage", "set_position_xyz_centimeters", "set_orientation_pyr_radians"
    STEP_INFO_COMPONENTS: ["trajectory_data"] # "trajectory_data"
    OBSERVATION_COMPONENTS: ["state_data", "control_data", "camera", "imu", "sonar"] # "state_data", "control_data", "camera", "imu", "sonar"... The type(s) of "camera" sensor is defined by CAMERA_PARAMETERS.RENDER_PASSES
    IS_READY_VELOCITY_THRESHOLD: 0.0
   
    CAMERA:
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 70.0
      RENDER_PASSES: ["final_color", "segmentation", "depth_glsl"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
      
    NAVMESH:
      AGENT_RADIUS: 20.0
      AGENT_HEIGHT: 20.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: 1.0
      AGENT_MAX_SLOPE: 0.1
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 400.0
      TILE_SIZE_UU: 300
      TILE_POOL_SIZE: 1024
      MAX_SIMPLIFICATION_ERROR: 1.3
      NAV_MODIFIER_OFFSET_X: 0.0
      NAV_MODIFIER_OFFSET_Y: 0.0
      NAV_MODIFIER_OFFSET_Z: 0.0
      WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]
      EXPORT_NAV_DATA_OBJ: False
      EXPORT_NAV_DATA_OBJ_DIR: ""
  
  VISUALIZER:
    ACTOR_NAME: "OpenBotAgent"
    SPAWN_CAMERA: False
    SPAWN_CAMERA_POSITION_X: -50.0
    SPAWN_CAMERA_POSITION_Y: 0.0
    SPAWN_CAMERA_POSITION_Z: 40.0
    SPAWN_CAMERA_ORIENTATION_PITCH: -35.0
    SPAWN_CAMERA_ORIENTATION_YAW: 0.0
    SPAWN_CAMERA_ORIENTATION_ROLL: 0.0
  
  SONAR_SENSOR:
    NUM_RAYS: 21
    MAX_REFLECTION_ANGLE: 45.0
    HORIZONTAL_FOV: 30.0
    VERTICAL_FOV: 10.0
    RANGE:
      MIN: 0.01
      MAX: 10.0
    NOISE_STD: 0.0
    DEBUG_RENDER: True

  IMU_SENSOR:
    ACCELEROMETER_NOISE_STD: 
      X: 0.0
      Y: 0.0
      Z: 0.0
    GYROSCOPE_NOISE_STD: 
      X: 0.0
      Y: 0.0
      Z: 0.0
    GYROSCOPE_BIAS: 
      X: 0.0
      Y: 0.0
      Z: 0.0
    DEBUG_RENDER: False
      
OPENBOT:
  OPENBOT_PAWN:
    SKELETAL_MESH: "/OpenBot/V1/Meshes/OpenBot_V1_Mesh.OpenBot_V1_Mesh"
    ANIM_INSTANCE: "/OpenBot/V1/Meshes/OpenBot_V1_Animation.OpenBot_V1_Animation_C"

    MOTOR_VELOCITY_CONSTANT: 65.89 # Velocity constant of the OpenBot motors
    GEAR_RATIO: 50.0               # Gear ratio of the OpenBot motors

    BATTERY_VOLTAGE: 12.0          # Voltage of the battery powering the OpenBot [V]
    CONTROL_DEAD_ZONE: 2.5         # Absolute duty cycle (in the ACTION_SCALE range) below which a command does not produces any torque on the vehicle
    MOTOR_TORQUE_MAX: 0.19         # Motor maximal torque [N.m]
    ELECTRICAL_RESISTANCE: 0.5     # Motor winding electrical resistance [Ohms]
    ELECTRICAL_INDUCTANCE: 0.5     # Motor winding electrical inductance [Henry]
    
    ACTION_SCALE: 255              # Action scaling factor

    VEHICLE_COMPONENT:
      MASS: 1.12                   # Mass of the vehicle chassis in [kg]
      DRAG_COEFFICIENT: 1.0        # DragCoefficient of the vehicle chassis
      CHASSIS_WIDTH: 15.0          # Chassis width used for drag force computation in [cm]
      CHASSIS_HEIGHT: 15.0         # Chassis height used for drag force computation in [cm]
      MOTOR_MAX_RPM: 20000.0       # Max RPM for engine

    CAMERA_COMPONENT:
      POSITION_X: 5.0              # Camera relative position in [cm]
      POSITION_Y: 5.0              # Camera relative position in [cm]
      POSITION_Z: 5.0              # Camera relative position in [cm]
      ROLL: 0.0                    # Camera relative orientation in [cm]
      YAW: 0.0                     # Camera relative orientation in [°]
      PITCH: 0.0                   # Camera relative orientation in [°]
      FOV: 70.0                    # Camera field of view in [°]
    
    IMU_COMPONENT:
      POSITION_X: 5.0              # IMU relative position in [cm]
      POSITION_Y: 0.0              # IMU relative position in [cm]
      POSITION_Z: 5.0              # IMU relative position in [cm]
      ROLL: 0.0                    # IMU relative orientation in [°]
      YAW: 0.0                     # IMU relative orientation in [°]
      PITCH: 0.0                   # IMU relative orientation in [°]
      
    SONAR_COMPONENT:
      POSITION_X: 10.0             # Sonar relative position in [cm]
      POSITION_Y: 0.0              # Sonar relative position in [cm]
      POSITION_Z: -1.5             # Sonar relative position in [cm]
      ROLL: 0.0                    # Sonar relative orientation in [°]
      YAW: 0.0                     # Sonar relative orientation in [°]
      PITCH: 0.0                   # Sonar relative orientation in [°]

  OPENBOT_WHEEL:
    AFFECTED_BY_HANDBRAKE: True
    SHAPE_RADIUS: 3.3              # Radius of the wheel in [cm]
    SHAPE_WIDTH: 2.5               # Width of the wheel in [cm]
    STEER_ANGLE: 0.0
    SUSPENSION_MAX_RAISE: 0.0      # How far the wheel can go above the resting position in [m]
    SUSPENSION_MAX_DROP: 0.0       # How far the wheel can drop below the resting position in [m]
    MASS: 0.033                    # Mass of this wheel in [kg]
