SIMULATION_CONTROLLER:
  IP: "127.0.0.1"
  PORT: 30000
  WORLD_PATH_NAME: "" # full path to the map including the repeated name, e.g., "/Game/Maps/NewMap.NewMap"
  LEVEL_NAME: ""      # full path to the map excluding the repeated name, e.g., "/Game/Maps/NewMap"
  SIMULATION_STEP_TIME_SECONDS: 0.1
  TASK: ""
  AGENT: ""
  CUSTOM_UNREAL_CONSOLE_COMMANDS: []

  CAMERA_AGENT:
    ACTION_COMPONENTS: ["set_pose", "set_num_random_points"] # "set_pose", "set_num_random_points"
    OBSERVATION_COMPONENTS: ["camera"] # "camera"
    STEP_INFO_COMPONENTS: ["random_points"] # "random_points"
    CAMERA:
      CAMERA_ACTOR_NAME: ""
      RENDER_PASSES: ["final_color"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0
    NAVMESH:
      AGENT_RADIUS: 1.0
      AGENT_HEIGHT: 1.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: -1.0
      AGENT_MAX_SLOPE: 1.0
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 0.0
      TILE_SIZE_UU: 1
      MAX_SIMPLIFICATION_ERROR: 1.3
      NAV_MODIFIER_OFFSET_X: 0.0
      NAV_MODIFIER_OFFSET_Y: 0.0
      NAV_MODIFIER_OFFSET_Z: 0.0
      WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]
      EXPORT_NAV_DATA_OBJ: False
      EXPORT_NAV_DATA_OBJ_DIR: ""

  OPENBOT_AGENT:
    OPENBOT_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["apply_voltage"] # "apply_voltage", "set_position_xyz_centimeters", "set_orientation_pyr_radians"
    OBSERVATION_COMPONENTS: ["state_data", "control_data", "camera"] # "state_data", "control_data", "camera"
    STEP_INFO_COMPONENTS: ["trajectory_data"]
    IS_READY_VELOCITY_THRESHOLD: 0.0
    CAMERA:
      RENDER_PASSES: ["final_color"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0
    TRAJECTORY_DATA:
      GOAL_ACTOR_NAME: ""
    NAVMESH:
      AGENT_RADIUS: 20.0
      AGENT_HEIGHT: 20.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: 2.0
      AGENT_MAX_SLOPE: 0.1
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 400.0
      TILE_SIZE_UU: 1
      MAX_SIMPLIFICATION_ERROR: 1.3
      WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]

  SPHERE_AGENT:
    SPHERE_ACTOR_NAME: "" # TODO: spawn this actor instead of finding it within the scene
    ACTION_COMPONENTS: ["apply_force"] # "apply_force"
    OBSERVATION_COMPONENTS: ["compass", "camera"] # "compass", "camera"
    STEP_INFO_COMPONENTS: ["debug_info"] # "debug_info"
    COMPASS:
      GOAL_ACTOR_NAME: ""
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0
      YAW_SCALE: 1.0
    CAMERA:
      CAMERA_ACTOR_NAME: ""
      RENDER_PASSES: ["final_color"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      FOV: 90.0
      POSITION_OFFSET_X: 0.0
      POSITION_OFFSET_Y: 0.0
      POSITION_OFFSET_Z: 5.0
    APPLY_FORCE:
      FORCE_SCALE: 1.0
      ROTATE_SCALE: 1.0
    SPHERE:
      MASS_SCALE: 1.0
      MAX_ANGULAR_VELOCITY: 1.0
      LINEAR_DAMPING: 0.0
      ANGULAR_DAMPING: 0.0

  IMITATION_LEARNING_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    GET_POSITIONS_FROM_TRAJECTORY_SAMPLING: TRUE
    POSITIONS_FILE: ""
    TRAJECTORY_SAMPLING_SEARCH_RADIUS: 10000
    TRAJECTORY_SAMPLING_MAX_ITERS: 10000

  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
      DISTANCE_TO_GOAL_SCALE: 1.0
    EPISODE_BEGIN:
      AGENT_POSITION_X_MIN: .NAN
      AGENT_POSITION_X_MAX: .NAN
      AGENT_POSITION_Y_MIN: .NAN
      AGENT_POSITION_Y_MAX: .NAN
      AGENT_POSITION_Z: .NAN
      GOAL_POSITION_X_MIN: .NAN
      GOAL_POSITION_X_MAX: .NAN
      GOAL_POSITION_Y_MIN: .NAN
      GOAL_POSITION_Y_MAX: .NAN
      GOAL_POSITION_Z: .NAN
      SPAWN_DISTANCE_THRESHOLD: 1.0

  VISUALIZER:
    ACTOR_NAME: ""
    SPAWN_CAMERA: true
    SPAWN_CAMERA_POSITION_X: 0.0
    SPAWN_CAMERA_POSITION_Y: 0.0
    SPAWN_CAMERA_POSITION_Z: 0.0
    SPAWN_CAMERA_ORIENTATION_PITCH: 0.0
    SPAWN_CAMERA_ORIENTATION_YAW: 0.0
    SPAWN_CAMERA_ORIENTATION_ROLL: 0.0

  # We have found these values achieve a good trade-off between image quality and
  # rendering speed. When Unreal defines ClampMin/ClampMax values, it will clamp
  # those values in the engine. When Unreal defines UIMin/UIMax vales, it will
  # only clamp those values values in the editor.
  CAMERA_SENSOR:
    FINAL_COLOR_OVERRIDE_AUTO_EXPOSURE_SPEED_UP: true
    FINAL_COLOR_AUTO_EXPOSURE_SPEED_UP: 9999.0                        # ClampMin=0.02, UIMax=20.0
    FINAL_COLOR_OVERRIDE_AUTO_EXPOSURE_SPEED_DOWN: true
    FINAL_COLOR_AUTO_EXPOSURE_SPEED_DOWN: 9999.0                      # ClampMin=0.02, UIMax=20.0
    FINAL_COLOR_OVERRIDE_INDIRECT_LIGHTING_INTENSITY: true
    FINAL_COLOR_INDIRECT_LIGHTING_INTENSITY: 0.0                      # set to 0.0 to use raytracing global illumination
    FINAL_COLOR_USE_RAYTRACING_IF_ENABLED: true                       # set to true to use UE Raytracing features
    FINAL_COLOR_OVERRIDE_RAYTRACING_GI: true
    FINAL_COLOR_RAYTRACING_GI_TYPE: "BruteForce"                      # set to "BruteForce" when using Raytracing
    FINAL_COLOR_OVERRIDE_RAYTRACING_GI_MAX_BOUNCES: true
    FINAL_COLOR_RAYTRACING_GI_MAX_BOUNCES: 4                          # ClampMin=1, ClampMax=64
    FINAL_COLOR_OVERRIDE_RAYTRACING_GI_SAMPLES_PER_PIXEL: true
    FINAL_COLOR_RAYTRACING_GI_SAMPLES_PER_PIXEL: 16                   # ClampMin=1, ClampMax=64
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO: True
    FINAL_COLOR_RAYTRACING_AO: 1                                      # set to 1 to enable and 0 to disable
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO_SAMPLES_PER_PIXEL: true
    FINAL_COLOR_RAYTRACING_AO_SAMPLES_PER_PIXEL: 8                    # ClampMin=1, ClampMax=64
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO_INTENSITY: true
    FINAL_COLOR_RAYTRACING_AO_INTENSITY: 0.8                          # ClampMin=0.0, ClampMax=1.0
    FINAL_COLOR_OVERRIDE_RAYTRACING_AO_RADIUS: true
    FINAL_COLOR_RAYTRACING_AO_RADIUS: 4000.0                          # ClampMin=0.0, ClampMax=10000.0
    FINAL_COLOR_OVERRIDE_REFLECTIONS_TYPE: true
    FINAL_COLOR_REFLECTIONS_TYPE: "RayTracing"                        # set to "RayTracing" when using Raytracing
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_MAX_BOUNCES: true
    FINAL_COLOR_RAYTRACING_REFLECTIONS_MAX_BOUNCES: 2                 # ClampMin=1, ClampMax=64
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_MAX_ROUGHNESS: true 
    FINAL_COLOR_RAYTRACING_REFLECTIONS_MAX_ROUGHNESS: 0.4             # ClampMin=0.01, ClampMax=1.0
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_SAMPLES_PER_PIXEL: true
    FINAL_COLOR_RAYTRACING_REFLECTIONS_SAMPLES_PER_PIXEL: 8           # ClampMin=1, ClampMax=64
    FINAL_COLOR_OVERRIDE_RAYTRACING_REFLECTIONS_TRANSLUCENCY: true
    FINAL_COLOR_RAYTRACING_REFLECTIONS_TRANSLUCENCY: 1                # set to 1 to enable and 0 to disable
    FINAL_COLOR_SET_AMBIENT_OCCLUSION: true                           # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_ANTI_ALIASING: true
    FINAL_COLOR_SET_CAMERA_IMPERFECTIONS: true                        # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_COLOR_GRADING: true                               # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_DEPTH_OF_FIELD: true                              # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_DISTANCE_FIELD_AO: true                           # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_RAYTRACED_DISTANCE_FIELD_SHADOWS: true
    FINAL_COLOR_SET_DYNAMIC_SHADOWS: true
    FINAL_COLOR_SET_EYE_ADAPTATION: true                              # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_GRAIN: true                                       # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_INDIRECT_LIGHTING_CACHE: true                     # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_LENS_FLARES: true                                 # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_LIGHT_SHAFTS: true                                # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_SCREEN_SPACE_REFLECTIONS: true                    # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_SEPARATE_TRANSLUCENCY: true                       # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_TEMPORAL_AA: true                                 # enabled by FEngineShowFlags::EnableAdvancedFeatures()
    FINAL_COLOR_SET_VIGNETTE: true                                    # enabled by FEngineShowFlags::EnableAdvancedFeatures()
