SIMULATION_CONTROLLER:
  IP: "127.0.0.1"
  PORT: 30000
  LEVEL_PATH: "/Game/Maps"
  LEVEL_PREFIX: "Map_"
  LEVEL_ID: ""
  SIMULATION_STEP_TIME_SECONDS: 0.1
  TASK: ""
  AGENT: ""
  CUSTOM_UNREAL_CONSOLE_COMMANDS: []

  CAMERA_AGENT:
    ACTION_COMPONENTS: ["set_pose", "set_num_random_points"] # "state_data", "control_data", "camera"
    OBSERVATION_COMPONENTS: ["camera"] # "camera"
    STEP_INFO_COMPONENTS: ["random_points"] # "random_points"
    CAMERA:
      CAMERA_ACTOR_NAME: ""
      RENDER_PASSES: ["final_color"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0
      FINAL_COLOR_AUTO_EXPOSURE_OVERRIDE_SPEED_UP: False
      FINAL_COLOR_AUTO_EXPOSURE_SPEED_UP: 0.0
      FINAL_COLOR_AUTO_EXPOSURE_OVERRIDE_SPEED_DOWN: False
      FINAL_COLOR_AUTO_EXPOSURE_SPEED_DOWN: 0.0
    NAVMESH:
      AGENT_RADIUS: 1.0
      AGENT_HEIGHT: 1.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: -1.0
      AGENT_MAX_SLOPE: 1.0
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 0.0
      TILE_SIZE_UU: 1
      MAX_SIMPLIFICATION_ERROR: 1.3
      NAV_MODIFIER_OFFSET_X: 0.0
      NAV_MODIFIER_OFFSET_Y: 0.0
      NAV_MODIFIER_OFFSET_Z: 0.0
      WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]
      EXPORT_NAV_DATA_OBJ: False
      EXPORT_NAV_DATA_OBJ_DIR: ""

  OPENBOT_AGENT:
    OPENBOT_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["apply_voltage"] # "apply_voltage", "set_position_xyz_centimeters", "set_orientation_pyr_radians"
    OBSERVATION_COMPONENTS: ["state_data", "control_data", "camera"] # "state_data", "control_data", "camera"
    STEP_INFO_COMPONENTS: ["trajectory_data"]
    IS_READY_VELOCITY_THRESHOLD: 0.0
    CAMERA:
      RENDER_PASSES: ["final_color"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0
    TRAJECTORY_DATA:
      GOAL_ACTOR_NAME: ""
    NAVMESH:
      AGENT_RADIUS: 20.0
      AGENT_HEIGHT: 20.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: 2.0
      AGENT_MAX_SLOPE: 0.1
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 400.0
      TILE_SIZE_UU: 1
      MAX_SIMPLIFICATION_ERROR: 1.3
      WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]

  SPHERE_AGENT:
    SPHERE_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["apply_force"] # "apply_force"
    OBSERVATION_COMPONENTS: ["compass", "camera"] # "compass", "camera"
    STEP_INFO_COMPONENTS: ["debug_info"]
    COMPASS:
      GOAL_ACTOR_NAME: ""
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0
      YAW_SCALE: 1.0
    CAMERA:
      CAMERA_ACTOR_NAME: ""
      RENDER_PASSES: ["final_color"] # "final_color", "segmentation", "depth_glsl", "normals", "lens_distortion" 
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      FOV: 90.0
      POSITION_OFFSET_X: 0.0
      POSITION_OFFSET_Y: 0.0
      POSITION_OFFSET_Z: 1.0
    APPLY_FORCE:
      FORCE_SCALE: 1.0
      ROTATE_SCALE: 1.0
    SPHERE:
      MASS_SCALE: 1.0
      MAX_ANGULAR_VELOCITY: 1.0
      LINEAR_DAMPING: 0.0
      ANGULAR_DAMPING: 0.0

  IMITATION_LEARNING_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    GET_POSITIONS_FROM_TRAJECTORY_SAMPLING: TRUE
    POSITIONS_FILE: ""
    TRAJECTORY_SAMPLING_SEARCH_RADIUS: 10000
    TRAJECTORY_SAMPLING_MAX_ITERS: 10000

  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
      DISTANCE_TO_GOAL_SCALE: 1.0
    EPISODE_BEGIN:
      AGENT_POSITION_X_MIN: .NAN
      AGENT_POSITION_X_MAX: .NAN
      AGENT_POSITION_Y_MIN: .NAN
      AGENT_POSITION_Y_MAX: .NAN
      AGENT_POSITION_Z: .NAN
      GOAL_POSITION_X_MIN: .NAN
      GOAL_POSITION_X_MAX: .NAN
      GOAL_POSITION_Y_MIN: .NAN
      GOAL_POSITION_Y_MAX: .NAN
      GOAL_POSITION_Z: .NAN
      SPAWN_DISTANCE_THRESHOLD: 1.0

  VISUALIZER:
    CAMERA_ACTOR_NAME: ""
    SPAWN_CAMERA: true
    SPAWN_CAMERA_POSITION_X: 0.0
    SPAWN_CAMERA_POSITION_Y: 0.0
    SPAWN_CAMERA_POSITION_Z: 0.0
    SPAWN_CAMERA_ORIENTATION_PITCH: 0.0
    SPAWN_CAMERA_ORIENTATION_YAW: 0.0
    SPAWN_CAMERA_ORIENTATION_ROLL: 0.0
