SIMULATION_CONTROLLER:
  IP: "127.0.0.1"
  PORT: 30000
  SIMULATION_STEP_TIME_SECONDS: 0.1
  ENABLE_VISUALIZER: True
  TASK_NAME: ""
  AGENT_CONTROLLER_NAME: ""


  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
      DISTANCE_TO_GOAL_SCALE: 1.0
    EPISODE_BEGIN:
      AGENT_POSITION_X_MIN: .NAN
      AGENT_POSITION_X_MAX: .NAN
      AGENT_POSITION_Y_MIN: .NAN
      AGENT_POSITION_Y_MAX: .NAN
      AGENT_POSITION_Z: .NAN
      GOAL_POSITION_X_MIN: .NAN
      GOAL_POSITION_X_MAX: .NAN
      GOAL_POSITION_Y_MIN: .NAN
      GOAL_POSITION_Y_MAX: .NAN
      GOAL_POSITION_Z: .NAN
      SPAWN_DISTANCE_THRESHOLD: 1.0
    OBSTACLE_IGNORE_ACTOR_NAMES: []
  

  OPENBOT_AGENT_CONTROLLER:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    OBSERVATION_MODE: "mixed" # "mixed" or "physical"
    ACTION_MODE: "" # "low_level_control" or "teleport"
    # - "yaw-x-y" the observation vector is set to be the vehicle's yaw, x position and y position in the world frame
    # - "dist-sin-cos" the observation vector is set to be the vehicle's distance to the goal, the cos and sin components of the relative yaw between the vehicle's front (x) axis and the vector connecting the vehicle to its goal
    PHYSICAL_OBSERVATION_MODE: "yaw-x-y"

    AGENT_READY_VELOCITY_THRESHOLD: 0.0
    MIXED_MODE:
      OBSERVATION_CAMERA_ACTOR_NAME: ""
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      SMARTPHONE_FOV: 90.0        # Field of view of the smartphone camera in [deg]
      MOTION_BLUR_AMOUNT: 0.0     # Strength of motion blur, 0:off, should be renamed to intensity
      MOTION_BLUR_MAX: 0.0        # Max distortion caused by motion blur, in percent of the screen width, 0:off
      POST_PROC_BLEND_WEIGHT: 0.0 # Range (0.0, 1.0) where 0 indicates no effect, 1 indicates full effect


  SPHERE_AGENT_CONTROLLER:
    OBSERVATION_MODE: "mixed" # "mixed" or "physical"
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    SPHERE:
      MASS_SCALE: 1.0
      MAX_ANGULAR_VELOCITY: 1.0
      LINEAR_DAMPING: 0.0
      ANGULAR_DAMPING: 0.0
    MIXED_MODE:
      OBSERVATION_CAMERA_ACTOR_NAME: ""
      SET_OBSERVATION_CAMERA_POSE_EGOCENTRIC: True
      IMAGE_HEIGHT: 128
      IMAGE_WIDTH: 128
      ACTION_APPLY_FORCE_SCALE: 1.0
      ACTION_ROTATE_OBSERVATION_CAMERA_SCALE: 1.0
      OBSERVATION_CAMERA_POSITION_OFFSET_X: 0.0
      OBSERVATION_CAMERA_POSITION_OFFSET_Y: 0.0
      OBSERVATION_CAMERA_POSITION_OFFSET_Z: 1.0
      YAW_SCALE: 1.0
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0
    PHYSICAL_MODE:
      ACTION_APPLY_FORCE_SCALE: 1.0
      OFFSET_TO_GOAL_SCALE: 1.0
      LINEAR_VELOCITY_SCALE: 1.0


  IMAGE_SAMPLING_AGENT_CONTROLLER:
    CAMERA_ACTOR_NAME: "IMAGE_SAMPLING_CAMERA"
    ACTION_MODE: "" # "sample_images" or "replay_sampled_images"
    IMAGE_TYPE: "" # "RGB" OR "seg"
    IMAGE_HEIGHT: 512
    IMAGE_WIDTH: 512
    EXPORT_NAV_DATA_POLY_CSV: False
    EXPORT_NAV_DATA_OBJ: False
    EXPORT_NAV_DATA_DEBUG_POSES: False
    DEBUG_POSES_DIR: ""
    DEBUG_POSES_NUM: 1
    NAVMESH:
      AGENT_HEIGHT: 1.0
      AGENT_RADIUS: 1.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: -1.0
      AGENT_MAX_SLOPE: 1.0
      HEIGHT_LIMIT: 190
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 0.0
      TILE_SIZE_UU: 1000
      NAV_BOUND_BOX_HEIGHT_ABOVE_MIN: 0.0

  SLAM_DATASET_AGENT_CONTROLLER:
    CAMERA_ACTOR_NAME: "IMAGE_SAMPLING_CAMERA"
    CAMERA_FOV: 75.0
    ACTION_MODE: "" # "get_ceiling_images" or "follow_trajectory"
    IMAGE_TYPE: "" # "rgb" OR "seg"
    IMAGE_HEIGHT: 480
    IMAGE_WIDTH: 852
    NAVMESH:
      AGENT_HEIGHT: 1.0
      AGENT_RADIUS: 1.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: -1.0
      HEIGHT_LIMIT: 190
    TRAJECTORY:
      PATH_WEIGHT_DIST: 1.0
      PATH_WEIGHT_NUM_WAYPOINTS: 1.0
      MAX_ITER_REPLAN: 50000
      TARGET_POS_X: 0.0
      TARGET_POS_Y: 0.0
      TARGET_POS_Z: 0.0
      START_POS_X: 0.0
      START_POS_Y: 0.0
      START_POS_Z: 0.0

  # Used in code/experiments/debug_synchronization_model/DebugProject
  DEBUG_AGENT_CONTROLLER:
    AGENT_ACTOR_NAME: "SphereActor"
    FIRST_OBSERVATION_CAMERA_ACTOR_NAME: "FirstObservationCamera"
    FIRST_OBSERVATION_CAMERA_ACTOR_HEIGHT: 512
    FIRST_OBSERVATION_CAMERA_ACTOR_WIDTH: 512
    SECOND_OBSERVATION_CAMERA_ACTOR_NAME: "SecondObservationCamera"
    SECOND_OBSERVATION_CAMERA_ACTOR_HEIGHT: 512
    SECOND_OBSERVATION_CAMERA_ACTOR_WIDTH: 512


  VISUALIZER:
    CAMERA_ACTOR_NAME: ""
    SET_CAMERA_POSE: False
    CAMERA_POSITION_X: .NAN
    CAMERA_POSITION_Y: .NAN
    CAMERA_POSITION_Z: .NAN
    CAMERA_PITCH: 0.0
    CAMERA_YAW: 0.0
    CAMERA_ROLL: 0.0
