OPENBOT:
  OPENBOT_PAWN:
    SKELETAL_MESH: "/OpenBot/V0/Meshes/OpenBot_V0_Mesh.OpenBot_V0_Mesh"
    ANIM_INSTANCE: "/OpenBot/V0/Meshes/OpenBot_V0_Animation.OpenBot_V0_Animation_C"

    MOTOR_VELOCITY_CONSTANT: 65.89 # Velocity constant of the OpenBot motors
    GEAR_RATIO: 50.0               # Gear ratio of the OpenBot motors

    BATTERY_VOLTAGE: 12.0          # Voltage of the battery powering the OpenBot [V]
    CONTROL_DEAD_ZONE: 2.5         # Absolute duty cycle (in the ACTION_SCALE range) below which a command does not produces any torque on the vehicle
    MOTOR_TORQUE_MAX: 0.19         # Motor maximal torque [N.m]
    ELECTRICAL_RESISTANCE: 0.5     # Motor winding electrical resistance [Ohms]
    ELECTRICAL_INDUCTANCE: 0.5     # Motor winding electrical inductance [Henry]
    
    ACTION_SCALE: 255              # Action scaling factor

    VEHICLE_COMPONENT:
      DRAG_COEFFICIENT: 1.0        # DragCoefficient of the vehicle chassis
      CHASSIS_WIDTH: 15.0          # Chassis width used for drag force computation in [cm]
      CHASSIS_HEIGHT: 15.0         # Chassis height used for drag force computation in [cm]
      MOTOR_MAX_RPM: 20000.0       # Max RPM for engine

    CAMERA_COMPONENT:
      POSITION_X: 5.0
      POSITION_Y: 5.0
      POSITION_Z: 5.0
      ROLL: 0.0
      YAW: 0.0
      PITCH: 0.0
      FOV: 90.0

  OPENBOT_WHEEL:
    AFFECTED_BY_HANDBRAKE: True
    SHAPE_RADIUS: 3.3              # Radius of the wheel in [m]
    SHAPE_WIDTH: 1.5               # Width of the wheel in [m]
    STEER_ANGLE: 0.0
    SUSPENSION_MAX_RAISE: 0.0      # How far the wheel can go above the resting position in [m]
    SUSPENSION_MAX_DROP: 0.0       # How far the wheel can drop below the resting position in [m]
    MASS: 0.033                    # Mass of this wheel in [kg]
