#
# Copyright(c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

SPEAR:
  # LAUNCH_MODE: "running_instance"
  LAUNCH_MODE: "standalone_executable"

  STANDALONE_EXECUTABLE: "C:/github/spear/cpp/unreal_projects/SpearSim/Standalone-Development/Windows/SpearSim/Binaries/Win64/SpearSim-Cmd.exe"

  CUSTOM_COMMAND_LINE_ARGUMENTS: []
  RENDER_OFFSCREEN: False
  WINDOW_RESOLUTION_X: 512
  WINDOW_RESOLUTION_Y: 512

  NUM_EXTRA_WARMUP_TICKS: 5
  RPC_CLIENT_INTERNAL_TIMEOUT_SECONDS: 10.0


SP_ENGINE:
  PORT: 30000

  TASK: "NullTask"
  AGENT: "CameraAgent"
  CUSTOM_UNREAL_CONSOLE_COMMANDS: []

  #
  # Unreal systems
  #

  PHYSICS:
    SIMULATION_STEP_TIME: 0.05
    ENABLE_ENHANCED_DETERMINISM: True
    ENABLE_SUBSTEPPING: True
    MAX_SUBSTEP_DELTA_TIME: 0.01
    MAX_SUBSTEPS: 100
