INTERIORSIM:
  LAUNCH_MODE: "standalone_executable"
  STANDALONE_EXECUTABLE: "C:/github/interiorsim/code/unreal_projects/RobotProject/Standalone-Development/WindowsNoEditor/RobotProject.exe"
  # STANDALONE_EXECUTABLE: "E:/nav_mesh_debug_isim/Standalone-Development/WindowsNoEditor/RobotProject.exe"
  TEMP_DIR: "C:/github/interiorsim/code/experimental/image_sampling/"
  # VULKAN_DEVICE_FILES: "/usr/share/vulkan/icd.d/nvidia_icd.json" # required only for Linux
  RPC_CLIENT_INTERNAL_TIMEOUT_SECONDS: 60.0
  RPC_CLIENT_INITIALIZE_CONNECTION_MAX_TIME_SECONDS: 240.0
  RPC_CLIENT_INITIALIZE_CONNECTION_SLEEP_TIME_SECONDS: 2.0
  CUSTOM_COMMAND_LINE_ARGUMENTS: [ "-dx12", "-RobotSimSettingPath=C:/github/interiorsim/code/unreal_plugins/RobotSim/setting/settings.json"]
  RENDER_OFFSCREEN: True

SIMULATION_CONTROLLER:
  TASK_NAME: "NullTask"
  AGENT_CONTROLLER_NAME: "CameraAgentController"

  CAMERA_AGENT_CONTROLLER:
    CAMERA_ACTOR_NAME: "IMAGE_SAMPLING_CAMERA"
    IMAGE_HEIGHT: 480 #160 #480
    IMAGE_WIDTH: 852 #284 #852
    FOV: 90.0
    RENDER_PASSES: ["final_color"] #, ["final_color", "segmentation"]
    WORLD_BOUND_TAG_NAMES: ["architecture", "furniture"]
    EXPORT_NAV_DATA_OBJ: True
    EXPORT_NAV_DATA_OBJ_DIR: "E:/debug_example_image_dataset"
    NAVMESH:
      AGENT_HEIGHT: 180.0
      AGENT_RADIUS: 5.0
      CELL_SIZE: 1.0
      CELL_HEIGHT: 1.0
      AGENT_MAX_STEP_HEIGHT: 1.0
      AGENT_MAX_SLOPE: 1.0
      MERGE_REGION_SIZE: 0.0
      MIN_REGION_AREA: 100.0
      TILE_SIZE_UU: 300
      NAV_MODIFIER_OFFSET_Z: 10.0

  VISUALIZER:
    CAMERA_ACTOR_NAME: "IMAGE_SAMPLING_CAMERA"

IMAGE_SAMPLING_EXPERIMENT:
  SEED: 19
  PITCH_LOW_DEG: 0.0
  PITCH_HIGH_DEG: 0.0
  YAW_LOW_DEG: -180.0
  YAW_HIGH_DEG: 180.0
  ROLL_LOW_DEG: 0.0
  ROLL_HIGH_DEG: 0.0
  EXPORT_NAV_DATA_DEBUG_POSES: True
  DEBUG_POSES_NUM: 1000000