#
# Copyright(c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

SIMULATION_CONTROLLER:

  INTERACTION_MODE: "programmatic" # "interactive", "programmatic"

  # Setting SCENE_ID and MAP_ID will load the following map: /Game/Scenes/SCENE_ID/Maps/MAP_ID.MAP_ID
  # If SCENE_ID is not set, the default map will be loaded. If MAP_ID is not set, it will be set to SCENE_ID.
  SCENE_ID: ""
  MAP_ID: ""

  IP: "127.0.0.1"
  PORT: 30000

  TASK: ""
  AGENT: ""
  CUSTOM_UNREAL_CONSOLE_COMMANDS: []

  #
  # Agents
  #

  CAMERA_AGENT:
    CAMERA_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["set_position", "set_rotation"] # "set_position", "set_rotation"
    OBSERVATION_COMPONENTS: ["camera"] # "camera"
    STEP_INFO_COMPONENTS: []
    SPAWN_MODE: "specify_pose" # "specify_pose", "specify_existing_actor"
    SPAWN_ACTOR_NAME: ""
    SPAWN_POSITION_X: 0.0
    SPAWN_POSITION_Y: 0.0
    SPAWN_POSITION_Z: 0.0
    SPAWN_PITCH: 0.0
    SPAWN_YAW: 0.0
    SPAWN_ROLL: 0.0
    CAMERA:
      RENDER_PASSES: ["final_color"] # "depth", "final_color", "normals", segmentation"
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0

  OPENBOT_AGENT:
    OPENBOT_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["apply_voltage"] # "apply_voltage", "set_position_xyz_centimeters", "set_orientation_pyr_radians"
    OBSERVATION_COMPONENTS: ["state_data", "control_data", "camera"] # "state_data", "control_data", "camera", "encoder", "imu", "sonar"
    STEP_INFO_COMPONENTS: ["trajectory_data"] # "trajectory_data"
    IS_READY_VELOCITY_THRESHOLD: 0.001
    SPAWN_MODE: "specify_pose" # "specify_pose", "specify_existing_actor"
    SPAWN_ACTOR_NAME: ""
    SPAWN_POSITION_X: 0.0
    SPAWN_POSITION_Y: 0.0
    SPAWN_POSITION_Z: 0.0
    SPAWN_PITCH: 0.0
    SPAWN_YAW: 0.0
    SPAWN_ROLL: 0.0
    CAMERA:
      RENDER_PASSES: ["final_color"] # "depth", "final_color", "normal", "segmentation" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0

  SPHERE_AGENT:
    SPHERE_ACTOR_NAME: ""
    CAMERA_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["add_rotation", "add_force"] # "add_rotation", "add_force"
    OBSERVATION_COMPONENTS: ["position", "rotation", "camera"] # "position", "rotation", "camera"
    STEP_INFO_COMPONENTS: ["debug"] # "debug"
    SPAWN_MODE: "specify_pose" # "specify_pose", "specify_existing_actor"
    SPAWN_ACTOR_NAME: ""
    SPAWN_POSITION_X: 0.0
    SPAWN_POSITION_Y: 0.0
    SPAWN_POSITION_Z: 0.0
    SPAWN_PITCH: 0.0
    SPAWN_YAW: 0.0
    SPAWN_ROLL: 0.0
    SPHERE:
      STATIC_MESH: "/Engine/BasicShapes/Sphere.Sphere"
      MATERIAL: "/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial"
      MESH_SCALE: 0.5
      MAX_ANGULAR_VELOCITY: 1.0
      LINEAR_DAMPING: 0.0
      ANGULAR_DAMPING: 0.0
    CAMERA:
      RENDER_PASSES: ["final_color"] # "depth", "final_color", "normal", "segmentation" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0
      POSITION_OFFSET_X: 0.0
      POSITION_OFFSET_Y: 0.0
      POSITION_OFFSET_Z: 5.0

  URDFBOT_AGENT:
    URDFBOT_ACTOR_NAME: ""
    ACTION_COMPONENTS: ["control_joints"]
    OBSERVATION_COMPONENTS: ["link_state", "camera"]
    STEP_INFO_COMPONENTS: []
    SPAWN_MODE: "specify_pose" # "specify_pose", "specify_existing_actor"
    SPAWN_ACTOR_NAME: ""
    SPAWN_POSITION_X: 0.0
    SPAWN_POSITION_Y: 0.0
    SPAWN_POSITION_Z: 0.0
    SPAWN_PITCH: 0.0
    SPAWN_YAW: 0.0
    SPAWN_ROLL: 0.0
    CAMERA:
      RENDER_PASSES: ["final_color"] # "depth", "final_color", "normal", "segmentation" 
      IMAGE_HEIGHT: 512
      IMAGE_WIDTH: 512
      FOV: 90.0
      POSITION_OFFSET_X: 0.0
      POSITION_OFFSET_Y: 0.0
      POSITION_OFFSET_Z: 0.0
    IS_READY_VELOCITY_THRESHOLD: 0.001

  #
  # Sensors
  #

  CAMERA_SENSOR:
    USE_SHARED_MEMORY: True # write image data to shared memory for fast interprocess communication
    READ_SURFACE_DATA: True # read image data from the GPU, useful for debugging and benchmarking

  IMU_SENSOR:
    DEBUG_RENDER: False

  SONAR_SENSOR:
    NUM_RAYS: 21
    MAX_REFLECTION_ANGLE: 45.0
    HORIZONTAL_FOV: 30.0
    VERTICAL_FOV: 10.0
    RANGE:
      MIN: 0.01
      MAX: 10.0
    DEBUG_RENDER: False

  #
  # Tasks
  #

  IMITATION_LEARNING_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    GET_POSITIONS_FROM_TRAJECTORY_SAMPLING: True
    POSITIONS_FILE: ""
    TRAJECTORY_SAMPLING_SEARCH_RADIUS: 10000.0 # Region around a sampled initial position to look for a reachable goal position
    TRAJECTORY_SAMPLING_MAX_ITERS: 100
    TRAJECTORY_SAMPLING_DEBUG_RENDER: False # Displays markers when set to True (only applies in Development builds)

  POINT_GOAL_NAV_TASK:
    AGENT_ACTOR_NAME: ""
    GOAL_ACTOR_NAME: ""
    GOAL_MESH: "/Engine/BasicShapes/Cylinder.Cylinder"
    GOAL_MATERIAL: "/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial"
    OBSTACLE_IGNORE_ACTOR_NAMES: []
    RANDOM_SEED: 0
    REWARD:
      HIT_GOAL: 1.0
      HIT_OBSTACLE: -1.0
    EPISODE_BEGIN:
      AGENT_POSITION_X_MIN: .NAN
      AGENT_POSITION_X_MAX: .NAN
      AGENT_POSITION_Y_MIN: .NAN
      AGENT_POSITION_Y_MAX: .NAN
      AGENT_POSITION_Z: .NAN
      GOAL_POSITION_X_MIN: .NAN
      GOAL_POSITION_X_MAX: .NAN
      GOAL_POSITION_Y_MIN: .NAN
      GOAL_POSITION_Y_MAX: .NAN
      GOAL_POSITION_Z: .NAN
      SPAWN_DISTANCE_THRESHOLD: 1.0

  #
  # Other top-level SimulationController classes
  #

  VISUALIZER:
    ACTOR_NAME: ""
    SPAWN_CAMERA: True
    SPAWN_CAMERA_POSITION_X: 0.0
    SPAWN_CAMERA_POSITION_Y: 0.0
    SPAWN_CAMERA_POSITION_Z: 0.0
    SPAWN_CAMERA_ORIENTATION_PITCH: 0.0
    SPAWN_CAMERA_ORIENTATION_YAW: 0.0
    SPAWN_CAMERA_ORIENTATION_ROLL: 0.0

  #
  # Unreal systems
  #

  PHYSICS:
    SIMULATION_STEP_TIME: 0.05
    ENABLE_ENHANCED_DETERMINISM: True
    ENABLE_SUBSTEPPING: True
    MAX_SUBSTEP_DELTA_TIME: 0.01
    MAX_SUBSTEPS: 100

  NAVMESH:
    AGENT_RADIUS: 1.0
    AGENT_HEIGHT: 1.0
    CELL_SIZE: 1.0
    CELL_HEIGHT: 1.0
    AGENT_MAX_STEP_HEIGHT: 1.0
    AGENT_MAX_SLOPE: 1.0
    MERGE_REGION_SIZE: 0.0
    MIN_REGION_AREA: 0.0
    TILE_SIZE_UU: 1
    TILE_POOL_SIZE: 1024
    MAX_SIMPLIFICATION_ERROR: 1.3
    EXPORT_NAV_DATA_OBJ: False
    EXPORT_NAV_DATA_OBJ_DIR: ""
