#
# Copyright(c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

SP_ENGINE:

  # INTERACTION_MODE: "programmatic" # "interactive", "programmatic"

  # # Setting SCENE_ID and MAP_ID will load the following map: /Game/Scenes/SCENE_ID/Maps/MAP_ID.MAP_ID
  # # If SCENE_ID is not set, the default map will be loaded. If MAP_ID is not set, it will be set to SCENE_ID.
  # SCENE_ID: ""
  # MAP_ID: ""

  IP: "127.0.0.1"
  PORT: 30000

  # CUSTOM_UNREAL_CONSOLE_COMMANDS: []