#
# Copyright(c) 2022 Intel. Licensed under the MIT License <http://opensource.org/licenses/MIT>.
#

SP_ENGINE:

  # Setting SCENE_ID and MAP_ID will load the following map: /Game/Scenes/SCENE_ID/Maps/MAP_ID.MAP_ID
  # If SCENE_ID is not set, the default map will be loaded. If MAP_ID is not set, it will be set to SCENE_ID.
  SCENE_ID: ""
  MAP_ID: ""

  PORT: 30000

  CUSTOM_UNREAL_CONSOLE_COMMANDS: []

  #
  # Unreal systems
  #

  PHYSICS:
    SIMULATION_STEP_TIME: 0.05
    ENABLE_ENHANCED_DETERMINISM: True
    ENABLE_SUBSTEPPING: True
    MAX_SUBSTEP_DELTA_TIME: 0.01
    MAX_SUBSTEPS: 100