name: Check style

on:
  pull_request:
    branches:
      - main

jobs:
  style-check:
    name: Style check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          sudo apt-get install --yes clang-format-10
          python -m pip install black
      - name: Check python style
        run: |
          black --check . --exclude 'code/experiments'
      - name: Check cpp style
        run: |
          ! find . -type f \( -name '*.h' -or -name '*.cpp' \) -not -ipath './code/experiments/*' | xargs clang-format -style=file --output-replacements-xml | grep -q 'replacement '
